repos:
- repo: git://github.com/pre-commit/mirrors-isort
  sha: 'v4.3.3'
  hooks:
  - id: isort
    args:
      - --recursive
      - --settings-path
      - ./setup.cfg
      - .
- repo: local
  hooks:
  - id: eslint
    name: eslint
    language: system
    entry: sh -c 'npm run eslint:fix'
    files: .js$
- repo: local
  hooks:
  - id: stylelint
    name: stylelint
    language: system
    entry: sh -c 'npm run stylelint:fix'
    files: .css$
- repo: local
  hooks:
  - id: yapf
    name: yapf
    language: python
    entry: yapf
    files: \.py$
    args: [-r, -e, "app/**/migrations/", app/dataviz/, app/app/]
