version: '3'

services:
  db:
    image: postgres:10.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  ipfs:
    image: ipfs/go-ipfs:release
    restart: unless-stopped
    volumes:
      - 'ipfsexport:/export'
      - 'ipfsdata:/data/ipfs'
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5001:5001"
      - "8080:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  web:
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code/app
    env_file:
      - app/app/.env
    build:
      context: .
      dockerfile: Dockerfile
    image: gitcoinco/web:latest
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3030:3030"
    depends_on:
      - db
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  testrpc:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: '-a 1 --seed 2 --host 0.0.0.0 --mnemonic "${TEST_MNEMONIC}"'
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  redis:
    restart: unless-stopped
    image: redis:4.0-alpine
    env_file:
      - app/app/.env
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

volumes:
  pgdata:
  ipfsdata:
  ipfsexport:
  redis:
