version: '3'

services:
  db:
    image: postgres:10.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    environment:
        - DATABASE_URL=postgres://postgres:postgres@db:5432?sslmode=disable
    links:
        - db
    ports:
        - "8081:8081"
    depends_on:
      - db
    restart: "on-failure:10"

  ipfs:
    image: ipfs/go-ipfs:release
    restart: unless-stopped
    volumes:
      - 'ipfsexport:/export'
      - 'ipfsdata:/data/ipfs'
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5001:5001"
      - "8080:8080"

  web:
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code/app
    env_file:
      - app/app/.env
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  testrpc:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    # command: "-a 1 --seed 2"
    command: "--host 0.0.0.0 --mnemonic 'lobster chair view oyster relax keep sell grab daring ankle lunar about'"

volumes:
  pgdata:
  ipfsdata:
  ipfsexport:
