# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/web
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: gitcoin/web:latest
        environment:
          CACHE_URL: dbcache://my_cache_table
          DATABASE_URL: psql://postgres:postgres@localhost/testdb
          REDIS_URL: rediscache://localhost:6379/0?client_class=django_redis.client.DefaultClient
          CACHEOPS_REDIS: redis://localhost:6379/0
          ENV: test
          COLLECTFAST_CACHE_URL: dbcache://collectfast

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

      - image: redis:4.0-alpine

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps37-{{ .Branch }}-{{ checksum "requirements/base.txt" }}
          # fallback to using the latest cache if no exact match is found
          - deps37-{{ .Branch }}-

      - run:
          name: install dependencies
          command: |
            echo "Using Python: $(which python)"
            echo "Working Directory: $PWD"
            python -m venv venv
            echo "Activating virtualenv..."
            . venv/bin/activate
            echo "Installing requirements..."
            pip install -r requirements/test.txt
            echo "Requirements installed!"

      - save_cache:
          key: deps37-{{ .Branch }}-{{ checksum "requirements/base.txt" }}
          paths:
            - ./venv
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            echo "Activating environment for tests..."
            . venv/bin/activate
            cd ~/web/app
            echo "Running pytest..."
            pytest -p no:ethereum
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
